-- AlterEnum: 4 new mobile-only homepage ad zones (two_column_home + home_right_column)
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_AFTER_MOVIE_GOSSIP_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_AFTER_TELANGANA_NEWS_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_AFTER_USA_SCHEDULE_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_AFTER_MOST_POPULAR_AD';
