-- AlterEnum
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_LATEST_NEWS_END_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_AFTER_TALK_OF_TOWN_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_AFTER_OPINION_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_MOBILE_BETWEEN_MOVIE_NEWS_GOSSIP_AD';
