-- AlterEnum
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_LATEST_NEWS_INLINE_AD';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_OPINION_BANNER';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_ARTICLE_WIDGET_AD';
ALTER TYPE "AdZone" ADD VALUE 'INNER_ARTICLE_MIDCONTENT_AD';
ALTER TYPE "AdZone" ADD VALUE 'INNER_SIDEBAR_BOTTOM_AD';
