-- AlterEnum
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_ABOVE_HEADER_BANNER';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_STRIP_BANNER_1';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_STRIP_BANNER_2';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_STRIP_BANNER_3';
ALTER TYPE "AdZone" ADD VALUE 'HOMEPAGE_BIG_STORY_BANNER';
